### ISSUE TITLE
Floating point lead time in SSM

### ISSUE THREAD

**Issue by DominikKamp** [LarrySnyder/stockpyl#115]
Executing program Demo.py
~~~

import stockpyl.supply_chain_network, stockpyl.supply_chain_node, stockpyl.demand_source, stockpyl.ssm_serial

network = stockpyl.supply_chain_network.SupplyChainNetwork()
network.add_node(stockpyl.supply_chain_node.SupplyChainNode(0, echelon_holding_cost=int(1), stockout_cost=int(1), lead_time=int(1), demand_source=stockpyl.demand_source.DemandSource(type='CD', round_to_int=True, demand_list=(int(0), int(1)), probabilities=(float(0.5), float(0.5)))))
S, C = stockpyl.ssm_serial.optimize_base_stock_levels(network=network)

print(S, C)

~~~
results in
~~~
Traceback (most recent call last):
  File "Demo.py", line 6, in <module>
    S, C = stockpyl.ssm_serial.optimize_base_stock_levels(network=network)
  File "stockpyl/ssm_serial.py", line 266, in optimize_base_stock_levels
    sum_ltd_dist = demand_source.lead_time_demand_distribution(float(np.sum(L)))
  File "stockpyl/demand_source.py", line 623, in lead_time_demand_distribution
    distribution = sum_of_discretes_distribution(lead_time, min_demand, max_demand, p)
  File "stockpyl/helpers.py", line 1016, in sum_of_discretes_distribution
    pk = convolve_many([p for _ in range(n)])
TypeError: 'float' object cannot be interpreted as an integer
~~~
although the given lead time is integral.

This is due to the floating point calculation of the accumulated lead time in https://github.com/LarrySnyder/stockpyl/blob/37d7628f1024674fc5e68beb7661f2729f1843bb/src/stockpyl/ssm_serial.py#L266 and can be resolved by using
~~~
	sum_ltd_dist = demand_source.lead_time_demand_distribution(sum(L))
~~~
instead.

**Comment by LarrySnyder** [comment]
@DominikKamp Thanks for these issues and the pull request. I will take a closer look in the next couple days!
